import os
import json
from dotenv import load_dotenv

load_dotenv()

SUGGESTION_PROMPT = """You are an expert Indian fixed income fund manager and risk advisor.

You have been given a PnL attribution report and anomaly signals for a bond portfolio.
Your task is to provide exactly 3 specific, actionable reallocation suggestions.

PORTFOLIO SUMMARY:
{portfolio_summary}

PnL ATTRIBUTION (period: {period}):
- Total PnL: ₹{total_pnl} Lacs
- Benchmark contribution: ₹{benchmark_pnl} Lacs  
- Spread (credit) contribution: ₹{spread_pnl} Lacs
- Spread % of total loss: {spread_pct}%

TOP DETRACTORS (biggest PnL losses):
{detractors}

ANOMALY SIGNALS:
{anomalies}

STRESS EXPOSURE:
{stress_exposure}

Based on this data, provide exactly 3 reallocation suggestions. Each suggestion must be actionable and specific.

Respond ONLY with a JSON array of exactly 3 objects. Each object must have these exact keys:
- "action": one of "REDUCE", "ADD", "SWITCH"
- "target": the ISIN, issuer name, or sector to act on
- "rationale": 2-3 sentence explanation citing specific numbers from the data
- "risk_note": one sentence on the key risk of this action
- "priority": one of "HIGH", "MEDIUM", "LOW"

Example format:
[
  {{
    "action": "REDUCE",
    "target": "DHFL bonds (INE202B07IK1, INE202B07HQ0)",
    "rationale": "DHFL contributed ₹-5,630 Lacs in spread losses, representing 99% of total portfolio loss. YTM has spiked to 25-30%, signalling near-certain default. Anomaly detection confirms sustained stress since Oct 2018.",
    "risk_note": "Selling at current distressed prices (25-30% YTM) may crystallise losses; consider staggered exit.",
    "priority": "HIGH"
  }}
]

Return ONLY the JSON array. No preamble, no explanation, no markdown backticks."""


def generate_suggestions(
    attribution_report: dict,
    anomalies_df,
    portfolio_df,
    anthropic_api_key: str = None,
) -> list[dict]:
    """
    Generate 3 AI reallocation suggestions for the fund manager.

    Uses Claude to synthesise:
    - PnL attribution report (deterministic numbers)
    - Anomaly signals (from Isolation Forest)
    - Portfolio stress exposure

    AI is used ONLY for reasoning — no numbers are generated by AI.
    Returns list of 3 suggestion dicts.
    """
    import pandas as pd

    # Build context strings from deterministic data
    summary = attribution_report.get("summary", {})

    # Portfolio summary
    stress_bonds = portfolio_df[portfolio_df["is_stress_issuer"] == True]
    stress_pct   = round(
        stress_bonds["face_value"].sum() / portfolio_df["face_value"].sum() * 100, 1
    )
    port_summary = (
        f"Total AUM: ₹{portfolio_df['face_value'].sum():,.0f} Lacs | "
        f"{len(portfolio_df)} bonds | "
        f"Stress issuer exposure: {stress_pct}% of AUM"
    )

    # Detractors
    detractors = attribution_report.get("top_detractors", [])
    det_str = "\n".join([
        f"- {d['issuer_name'][:40]} ({d['isin']}): "
        f"₹{d['total_pnl']:,.2f}L total, ₹{d['spread_pnl']:,.2f}L from spread"
        for d in detractors
    ])

    # Anomalies
    if hasattr(anomalies_df, "to_dict") and not anomalies_df.empty and "confirmed_anomaly" in anomalies_df.columns:
        anom_rows = anomalies_df[anomalies_df["confirmed_anomaly"] == 1].head(5)
        anom_str = "\n".join([
            f"- {row['isin']}: YTM {row['avg_ytm']:.1f}%, "
            f"spread {row['spread_bps']:.0f}bps, "
            f"score {row['anomaly_score_norm']:.3f}"
            for _, row in anom_rows.iterrows()
        ]) if len(anom_rows) else "No confirmed anomalies in current window."
    else:
        anom_str = "Anomaly data not available."

    # Stress exposure detail
    stress_str = "\n".join([
        f"- {row['issuer_name'][:40]} ({row['isin']}): "
        f"₹{row['face_value']:,}L ({row['weight']:.1f}% of portfolio), "
        f"Tag: {row['stress_tag']}"
        for _, row in stress_bonds.iterrows()
    ]) if len(stress_bonds) else "No stress issuers in portfolio."

    prompt = SUGGESTION_PROMPT.format(
        portfolio_summary = port_summary,
        period            = "2018-2019 DHFL stress period",
        total_pnl         = f"{summary.get('total_pnl_lacs', 0):,.2f}",
        benchmark_pnl     = f"{summary.get('benchmark_pnl_lacs', 0):,.2f}",
        spread_pnl        = f"{summary.get('spread_pnl_lacs', 0):,.2f}",
        spread_pct        = f"{summary.get('spread_pct_of_total', 0):.1f}",
        detractors        = det_str,
        anomalies         = anom_str,
        stress_exposure   = stress_str,
    )

    # Try Claude API
    api_key = anthropic_api_key or os.getenv("ANTHROPIC_API_KEY", "")

    if api_key and api_key != "your_anthropic_api_key":
        try:
            import anthropic
            client = anthropic.Anthropic(api_key=api_key)
            message = client.messages.create(
                model="claude-haiku-4-5",
                max_tokens=1000,
                messages=[{"role": "user", "content": prompt}]
            )
            raw = message.content[0].text.strip()
            # Strip markdown fences if present
            raw = raw.replace("```json", "").replace("```", "").strip()
            suggestions = json.loads(raw)
            if isinstance(suggestions, list) and len(suggestions) == 3:
                print(f"[suggestions] Generated {len(suggestions)} AI suggestions")
                return suggestions
        except Exception as e:
            print(f"[suggestions] LLM call failed: {e}, using fallback.")

    # Deterministic fallback — no API needed
    return _fallback_suggestions(attribution_report, portfolio_df)


def _fallback_suggestions(attribution_report: dict, portfolio_df) -> list[dict]:
    """Rule-based fallback when Claude API is unavailable."""
    detractors = attribution_report.get("top_detractors", [])
    summary    = attribution_report.get("summary", {})
    spread_pct = summary.get("spread_pct_of_total", 0)

    suggestions = []

    # Suggestion 1: Reduce worst detractor
    if detractors:
        worst = detractors[0]
        suggestions.append({
            "action":   "REDUCE",
            "target":   f"{worst['issuer_name'][:40]} ({worst['isin']})",
            "rationale": (
                f"This bond contributed ₹{worst['total_pnl']:,.2f}L in losses, "
                f"with ₹{worst['spread_pnl']:,.2f}L from credit spread widening. "
                f"Spread losses represent {spread_pct:.0f}% of total portfolio loss, "
                f"indicating severe credit deterioration."
            ),
            "risk_note": "Selling at distressed levels crystallises losses; consider staggered exit.",
            "priority": "HIGH",
        })

    # Suggestion 2: Add high-quality sovereign/AAA exposure
    aaa_bonds = portfolio_df[portfolio_df["rating"] == "AAA"]
    if len(aaa_bonds):
        top_aaa = aaa_bonds.iloc[0]
        suggestions.append({
            "action":   "ADD",
            "target":   f"AAA-rated sovereign/PSU bonds (e.g. {top_aaa['issuer_name'][:30]})",
            "rationale": (
                f"Portfolio has {(portfolio_df['is_stress_issuer'].sum() / len(portfolio_df) * 100):.0f}% "
                f"stress issuer exposure. Rotating into AAA PSU bonds reduces credit risk "
                f"while maintaining yield. Current AAA benchmark yields of 7-8% offer "
                f"adequate compensation with minimal default risk."
            ),
            "risk_note": "AAA bonds have higher duration risk; rising rates will impact mark-to-market.",
            "priority": "MEDIUM",
        })

    # Suggestion 3: Diversify NBFC concentration
    suggestions.append({
        "action":   "SWITCH",
        "target":   "NBFC exposure → diversified sectors (infra, PSU banks)",
        "rationale": (
            f"Portfolio is concentrated in NBFC/HFC sector with {len(portfolio_df[portfolio_df['is_stress_issuer']])} "
            f"stress issuers. The NBFC liquidity crisis of 2018-19 demonstrated sector-wide "
            f"contagion risk. Switching to infrastructure bonds or PSU bank bonds reduces "
            f"sector concentration and improves credit quality."
        ),
        "risk_note": "Infrastructure bonds may have lower liquidity in secondary markets.",
        "priority": "MEDIUM",
    })

    return suggestions[:3]